/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.cuadra.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Chat type.
 */
public class Chat {
    private String model;
    private List<ContentEx> content;
    private String chatId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Chat() {
    }

    /**
     * Initialization constructor.
     * @param  model  String value for model.
     * @param  content  List of ContentEx value for content.
     * @param  chatId  String value for chatId.
     */
    public Chat(
            String model,
            List<ContentEx> content,
            String chatId) {
        this.model = model;
        this.content = content;
        this.chatId = chatId;
    }

    /**
     * Getter for Model.
     * Model name
     * @return Returns the String
     */
    @JsonGetter("model")
    public String getModel() {
        return model;
    }

    /**
     * Setter for Model.
     * Model name
     * @param model Value for String
     */
    @JsonSetter("model")
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for Content.
     * Request content
     * @return Returns the List of ContentEx
     */
    @JsonGetter("content")
    public List<ContentEx> getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * Request content
     * @param content Value for List of ContentEx
     */
    @JsonSetter("content")
    public void setContent(List<ContentEx> content) {
        this.content = content;
    }

    /**
     * Getter for ChatId.
     * If you want to keep context between request, otherwise leave it empty, you get one with every
     * chat you create.
     * @return Returns the String
     */
    @JsonGetter("chatId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChatId() {
        return chatId;
    }

    /**
     * Setter for ChatId.
     * If you want to keep context between request, otherwise leave it empty, you get one with every
     * chat you create.
     * @param chatId Value for String
     */
    @JsonSetter("chatId")
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Chat into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Chat [" + "model=" + model + ", content=" + content + ", chatId=" + chatId
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Chat.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Chat.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(model, content)
                .chatId(getChatId());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Chat}.
     */
    public static class Builder {
        private String model;
        private List<ContentEx> content;
        private String chatId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  model  String value for model.
         * @param  content  List of ContentEx value for content.
         */
        public Builder(String model, List<ContentEx> content) {
            this.model = model;
            this.content = content;
        }

        /**
         * Setter for model.
         * @param  model  String value for model.
         * @return Builder
         */
        public Builder model(String model) {
            this.model = model;
            return this;
        }

        /**
         * Setter for content.
         * @param  content  List of ContentEx value for content.
         * @return Builder
         */
        public Builder content(List<ContentEx> content) {
            this.content = content;
            return this;
        }

        /**
         * Setter for chatId.
         * @param  chatId  String value for chatId.
         * @return Builder
         */
        public Builder chatId(String chatId) {
            this.chatId = chatId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Chat} object using the set fields.
         * @return {@link Chat}
         */
        public Chat build() {
            Chat model2 =
                    new Chat(model, content, chatId);
            model2.additionalProperties = additionalProperties;
            return model2;
        }
    }
}
