/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.cuadra.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TokensEx type.
 */
public class TokensEx {
    private Integer inputTokens;
    private Integer outputTokens;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TokensEx() {
    }

    /**
     * Initialization constructor.
     * @param  inputTokens  Integer value for inputTokens.
     * @param  outputTokens  Integer value for outputTokens.
     */
    public TokensEx(
            Integer inputTokens,
            Integer outputTokens) {
        this.inputTokens = inputTokens;
        this.outputTokens = outputTokens;
    }

    /**
     * Getter for InputTokens.
     * Number of tokens of the request input
     * @return Returns the Integer
     */
    @JsonGetter("inputTokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getInputTokens() {
        return inputTokens;
    }

    /**
     * Setter for InputTokens.
     * Number of tokens of the request input
     * @param inputTokens Value for Integer
     */
    @JsonSetter("inputTokens")
    public void setInputTokens(Integer inputTokens) {
        this.inputTokens = inputTokens;
    }

    /**
     * Getter for OutputTokens.
     * Number of tokens of the response output
     * @return Returns the Integer
     */
    @JsonGetter("outputTokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getOutputTokens() {
        return outputTokens;
    }

    /**
     * Setter for OutputTokens.
     * Number of tokens of the response output
     * @param outputTokens Value for Integer
     */
    @JsonSetter("outputTokens")
    public void setOutputTokens(Integer outputTokens) {
        this.outputTokens = outputTokens;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TokensEx into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TokensEx [" + "inputTokens=" + inputTokens + ", outputTokens=" + outputTokens
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TokensEx.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TokensEx.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .inputTokens(getInputTokens())
                .outputTokens(getOutputTokens());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TokensEx}.
     */
    public static class Builder {
        private Integer inputTokens;
        private Integer outputTokens;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for inputTokens.
         * @param  inputTokens  Integer value for inputTokens.
         * @return Builder
         */
        public Builder inputTokens(Integer inputTokens) {
            this.inputTokens = inputTokens;
            return this;
        }

        /**
         * Setter for outputTokens.
         * @param  outputTokens  Integer value for outputTokens.
         * @return Builder
         */
        public Builder outputTokens(Integer outputTokens) {
            this.outputTokens = outputTokens;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TokensEx} object using the set fields.
         * @return {@link TokensEx}
         */
        public TokensEx build() {
            TokensEx model =
                    new TokensEx(inputTokens, outputTokens);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
