/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.cuadra.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for UsageCalculationEx type.
 */
public class UsageCalculationEx {
    private Integer estimatedTokens;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UsageCalculationEx() {
    }

    /**
     * Initialization constructor.
     * @param  estimatedTokens  Integer value for estimatedTokens.
     */
    public UsageCalculationEx(
            Integer estimatedTokens) {
        this.estimatedTokens = estimatedTokens;
    }

    /**
     * Getter for EstimatedTokens.
     * Estimated tokens for your request
     * @return Returns the Integer
     */
    @JsonGetter("estimatedTokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getEstimatedTokens() {
        return estimatedTokens;
    }

    /**
     * Setter for EstimatedTokens.
     * Estimated tokens for your request
     * @param estimatedTokens Value for Integer
     */
    @JsonSetter("estimatedTokens")
    public void setEstimatedTokens(Integer estimatedTokens) {
        this.estimatedTokens = estimatedTokens;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UsageCalculationEx into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsageCalculationEx [" + "estimatedTokens=" + estimatedTokens
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UsageCalculationEx.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UsageCalculationEx.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .estimatedTokens(getEstimatedTokens());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UsageCalculationEx}.
     */
    public static class Builder {
        private Integer estimatedTokens;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for estimatedTokens.
         * @param  estimatedTokens  Integer value for estimatedTokens.
         * @return Builder
         */
        public Builder estimatedTokens(Integer estimatedTokens) {
            this.estimatedTokens = estimatedTokens;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UsageCalculationEx} object using the set fields.
         * @return {@link UsageCalculationEx}
         */
        public UsageCalculationEx build() {
            UsageCalculationEx model =
                    new UsageCalculationEx(estimatedTokens);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
