/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.cuadra.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for UsageEx type.
 */
public class UsageEx {
    private TokensEx billedTokens;
    private TokensEx usedTokens;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UsageEx() {
    }

    /**
     * Initialization constructor.
     * @param  billedTokens  TokensEx value for billedTokens.
     * @param  usedTokens  TokensEx value for usedTokens.
     */
    public UsageEx(
            TokensEx billedTokens,
            TokensEx usedTokens) {
        this.billedTokens = billedTokens;
        this.usedTokens = usedTokens;
    }

    /**
     * Getter for BilledTokens.
     * Tokens used
     * @return Returns the TokensEx
     */
    @JsonGetter("billedTokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TokensEx getBilledTokens() {
        return billedTokens;
    }

    /**
     * Setter for BilledTokens.
     * Tokens used
     * @param billedTokens Value for TokensEx
     */
    @JsonSetter("billedTokens")
    public void setBilledTokens(TokensEx billedTokens) {
        this.billedTokens = billedTokens;
    }

    /**
     * Getter for UsedTokens.
     * Tokens used
     * @return Returns the TokensEx
     */
    @JsonGetter("usedTokens")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TokensEx getUsedTokens() {
        return usedTokens;
    }

    /**
     * Setter for UsedTokens.
     * Tokens used
     * @param usedTokens Value for TokensEx
     */
    @JsonSetter("usedTokens")
    public void setUsedTokens(TokensEx usedTokens) {
        this.usedTokens = usedTokens;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UsageEx into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsageEx [" + "billedTokens=" + billedTokens + ", usedTokens=" + usedTokens
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UsageEx.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UsageEx.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .billedTokens(getBilledTokens())
                .usedTokens(getUsedTokens());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UsageEx}.
     */
    public static class Builder {
        private TokensEx billedTokens;
        private TokensEx usedTokens;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for billedTokens.
         * @param  billedTokens  TokensEx value for billedTokens.
         * @return Builder
         */
        public Builder billedTokens(TokensEx billedTokens) {
            this.billedTokens = billedTokens;
            return this;
        }

        /**
         * Setter for usedTokens.
         * @param  usedTokens  TokensEx value for usedTokens.
         * @return Builder
         */
        public Builder usedTokens(TokensEx usedTokens) {
            this.usedTokens = usedTokens;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UsageEx} object using the set fields.
         * @return {@link UsageEx}
         */
        public UsageEx build() {
            UsageEx model =
                    new UsageEx(billedTokens, usedTokens);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
